# CivilServant gratitude
[gratitude]
campaign_tracking = "gratitude_2018"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[gratitude.banners.combi]
filename = "./gratitude/banner_combi.js"
pagename = "B18WMDE_grat_combi"
tracking = "CS18_grat_combi_1"

# Authors Campaign
[authors]
campaign_tracking = "WMDE_neweditors_summer2018"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[authors.banners.one]
filename = "./authors/banner01.js"
pagename = "B18WMDE_authors_02_180801_one"
tracking = "WMDE_neweditors_summer2018_1"

[authors.banners.two]
filename = "./authors/banner02.js"
pagename = "B18WMDE_authors_02_180801_two"
tracking = "WMDE_neweditors_summer2018_2"

[authors.banners.three]
filename = "./authors/banner03.js"
pagename = "B18WMDE_authors_02_180801_three"
tracking = "WMDE_neweditors_summer2018_3"
